version: "3.2"

services:
  install:
    image: jekyll/jekyll:builder

    command: bundle install

    volumes:
      - ./src:/srv/jekyll
      - ./src/vendor/bundle:/usr/local/bundle

  build:
    image: jekyll/jekyll:builder

    command: bundle exec jekyll build

    volumes:
      - ./src:/srv/jekyll
      - ./src/vendor/bundle:/usr/local/bundle

  serve:
    image: jekyll/jekyll:builder

    command: bundle exec jekyll serve --watch --incremental --force_polling

    ports:
      - "4000:4000"

    volumes:
      - ./src:/srv/jekyll
      - ./src/vendor/bundle:/usr/local/bundle