version: 2

workflows:
  version: 2

  workflow:
    jobs:
      - compile
                  
jobs:
  compile:
    docker:
      - image: circleci/ruby:2.5
    
    steps:
      - checkout

      - run:
          name: Move to /src Directory
          command: ls -al && cd ./src && ls -al

      - restore_cache:
          keys:
            - gemfile-v1-{{ checksum "./src/Gemfile.lock" }}
            - gemfile-v1-default

      - run:
          name: Install Ruby Dependencies
          command: |
            ls -al
            bundle check || bundle install

      - save_cache:
          key: gemfile-v1-{{ checksum "./src/Gemfile.lock" }}
          paths:
            - src/vendor/bundle

      # - run:
      #     name: Compile Jekyll Site
      #     command: docker-compose run --rm build