version: 2

workflows:
  version: 2

  workflow:
    jobs:
      - compile

      - publish:
          requires:
            - compile
          
          filters:
            branches:
              only:
                - master
                  
jobs:
  compile:
    docker:
      - image: derrysmith/circle-jekyll:latest
    
    steps:
      - checkout

      - restore_cache:
          keys:
            - ruby-dependencies-v1-{{ checksum "./src/Gemfile.lock" }}
            - ruby-dependencies-v1-

      - run:
          name: Install Ruby Dependencies
          command: bundle check --gemfile=./src/Gemfile || bundle install --gemfile=./src/Gemfile

      - save_cache:
          key: ruby-dependencies-v1-{{ checksum "./src/Gemfile.lock" }}
          paths:
            - /usr/local/bundle

      - run:
          name: Compile Jekyll Site
          command: bundle exec --gemfile=./src/Gemfile "jekyll build --config=./src/_config.yml --source=./src"

      - persist_to_workspace:
          root: ./
          paths:
            - _site
            - .firebaserc
            - firebase.json
  publish:
    docker:
      - image: derrysmith/circle-jekyll:latest
    
    steps:
      - attach_workspace:
          at: ./
      
      - run:
          name: Deploy to Firebase Hosting
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive