version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:latest-node
      #- image: derrysmith/cwentzel-build:latest
    steps:
      - run:
          name: install jekyll
          command: gem install jekyll
      
      - run:
          name: install firebase
          command: npm install -g firebase-tools --unsafe-perm
      
      - checkout
      
      - run:
          name: compile
          command: jekyll build
      # - run:
      #     name: publish
      #     command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting