version: 2

workflows:
  version: 2

  workflow:
    jobs:
      - compile
                  
jobs:
  compile:
    machine:
      - image: jekyll/jekyll:builder
    
    steps:
      - checkout

      - run:
          name: Compile Jekyll Site
          command: docker-compose run --rm build