version: 2

workflows:
  version: 2

  workflow:
    jobs:
      - compile
                  
jobs:
  compile:
    docker:
      - image: circleci/ruby:latest-node
    
    steps:
      - checkout

      - restore_cache:
          keys:
            - gemfile-v1-{{ checksum "./src/Gemfile.lock" }}
            - gemfile-v1-

      - run:
          name: Install Ruby Dependencies
          command: |
            cd ./src
            gem install bundler:2.0.2
            bundle check || bundle install

      - save_cache:
          key: gemfile-v1-{{ checksum "./src/Gemfile.lock" }}
          paths:
            - /usr/local/bundle

      - run:
          name: Compile Jekyll Site
          command: |
            cd ./src
            bundle exec jekyll build