version: 2

jobs:
  build:
    docker:
      #- image: circleci/ruby:latest-node
      - image: starefossen/ruby-node:latest
      #- image: derrysmith/cwentzel-build:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - app-dependencies-{{ checksum "Gemfile.lock" }}
            - app-dependencies-
      
      - run:
          name: install ruby dependencies
          command: bundle install
      
      # - run:
      #     name: install node dependencies
      #     command: npm install -g firebase-tools --unsafe-perm
      - save_cache:
          paths:
            - /usr/local/bundle
            - /usr/local/lib/node_modules
          key: app-dependencies-{{ checksum "Gemfile.lock" }}
      
      - run:
          name: compile
          command: bundle exec jekyll build --verbose
      # - run:
      #     name: publish
      #     command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting