version: 2

jobs:
  build:
    docker:
      #- image: starefossen/ruby-node
      - image: derrysmith/cwentzel-build:latest
    steps:
      - checkout
      
      - run:
          name: compile
          command: jekyll build
      # - run:
      #     name: publish
      #     command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting