version: 2

jobs:
  build:
    docker:
      - image: ruby:latest
      #- image: derrysmith/cwentzel-build:latest
    steps:
      - run:
          name: install jekyll
          command: |
            gem install jekyll
            gem install bundler -v 2.0.2
      
      - run:
          name: install firebase
          command: npm install -g firebase-tools --unsafe-perm
      
      - checkout
      
      - run:
          name: compile
          command: jekyll build
      # - run:
      #     name: publish
      #     command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting