version: 2

workflows:
  version: 2

  workflow:
    jobs:
      - compile
                  
jobs:
  compile:
    machine: true
    
    steps:
      - checkout

      - run:
          name: Install Ruby Dependencies
          command: docker-compose run --rm install

      - run:
          name: Compile Jekyll Site
          command: docker-compose run --rm build