name: build-and-deploy

on: push

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@master
      # - name: Build the site in the jekyll/builder container
      #   run: |
      #     docker run \
      #     -v ${{ github.workspace }}:/srv/jekyll \
      #     -v ${{ github.workspace }}/_site:/srv/jekyll/_site jekyll/builder:latest /bin/bash \
      #     -c "chmod 777 /srv/jekyll && jekyll build --future"