name: build

on:
  push:
    branches:
      - master

jobs:
  compile:
    # use an image that has jekyll already installed on it
    runs-on: ubuntu-latest
    steps:
    - name: install jekyll cli
      uses: faph/action-jekyll@v0.1
    - uses: actions/checkout@v1
    - name: build to _site folder
      run: jekyll build
  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: deploy to firebase
  #     run: echo "deploying _site folder to firebase hosting"